import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { DataProvider } from '@/store/context/DataContext';




const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link 
          rel="stylesheet" 
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" 
        />
      </head>
      <body
        className={`${roboto.variable} antialiased`}
      >
        <DataProvider>
          <div className="flex w-full bg-gray-100">
            {children}
          </div>
        </DataProvider>
      </body>
    </html>
  );
}
